import "~/styles/globals.css";
import bdo from "../assets/png/bdoAssets/BlackSpiritIcon.png";

import { GeistSans } from "geist/font/sans";

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

function TopNav() {
  return (
    <nav className="flex w-full items-center justify-center border-b p-5 text-5xl font-semibold bg-black">
      <div className="flex">
        <span>BD</span>
        <img src={bdo.src} className="h-11 w-11 m-1" />
        <span>dle</span>
      </div>
    </nav>
  );
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body className="flex flex-col gap-4">
        <TopNav />
        {children}
      </body>
    </html >
  );
}
